In [1]:
#get specific column using get
import pandas as pd
df=pd.read_csv("weather_1.csv")
df

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51

In [2]:
print(df.get("TemperatureF"))

0     30.9
1     30.0
2     28.9
3     33.1
4     30.9
5     32.0
6     28.9
7     33.1
8     37.9
9     41.0
10    46.0
11    46.9
12    53.1
13    55.0
14    57.0
15    55.9
16    57.0
17    55.9
18    54.0
19    52.0
20    51.1
21    48.0
22    46.9
23    46.0
Name: TemperatureF, dtype: float64

In [3]:
print(df.get(["TemperatureF","TimeEST"]))

    TemperatureF   TimeEST
0           30.9  12:51 AM
1           30.0   1:51 AM
2           28.9   2:51 AM
3           33.1   3:51 AM
4           30.9   4:51 AM
5           32.0   5:51 AM
6           28.9   6:51 AM
7           33.1   7:51 AM
8           37.9   8:51 AM
9           41.0   9:51 AM
10          46.0  10:51 AM
11          46.9  11:51 AM
12          53.1  12:51 PM
13          55.0   1:51 PM
14          57.0   2:51 PM
15          55.9   3:51 PM
16          57.0   4:51 PM
17          55.9   5:51 PM
18          54.0   6:51 PM
19          52.0   7:51 PM
20          51.1   8:51 PM
21          48.0   9:51 PM
22          46.9  10:51 PM
23          46.0  11:51 PM

In [4]:
df

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51

In [5]:
#slicing and dicing
print(df.loc[0])

TimeEST                         12:51 AM
TemperatureF                        30.9
Dew PointF                          27.0
Humidity                              85
Sea Level PressureIn               30.35
VisibilityMPH                         10
Wind Direction                      Calm
Wind SpeedMPH                       Calm
Gust SpeedMPH                          -
PrecipitationIn                      NaN
Events                               NaN
Conditions                 Partly Cloudy
WindDirDegrees                         0
DateUTC                 21-02-2012 05:51
Name: 0, dtype: object

In [6]:
print(df.loc[:,["Humidity"]])

    Humidity
0         85
1         85
2         85
3         75
4         82
5         79
6         89
7         82
8         73
9         70
10        56
11        52
12        50
13        55
14        55
15        57
16        59
17        64
18        69
19        74
20        77
21        80
22        83
23        83

In [7]:
print(df.loc[[1,5],["Humidity","Sea Level PressureIn"]])

   Humidity  Sea Level PressureIn
1        85                 30.35
5        79                 30.30

In [8]:
print(df.iloc[1])

TimeEST                          1:51 AM
TemperatureF                        30.0
Dew PointF                          26.1
Humidity                              85
Sea Level PressureIn               30.35
VisibilityMPH                         10
Wind Direction                      Calm
Wind SpeedMPH                       Calm
Gust SpeedMPH                          -
PrecipitationIn                      NaN
Events                               NaN
Conditions                 Partly Cloudy
WindDirDegrees                         0
DateUTC                 21-02-2012 06:51
Name: 1, dtype: object

In [9]:
print(df.iloc[[1],[0]])

   TimeEST
1  1:51 AM

In [10]:
print(df.iloc[:,[0]])

     TimeEST
0   12:51 AM
1    1:51 AM
2    2:51 AM
3    3:51 AM
4    4:51 AM
5    5:51 AM
6    6:51 AM
7    7:51 AM
8    8:51 AM
9    9:51 AM
10  10:51 AM
11  11:51 AM
12  12:51 PM
13   1:51 PM
14   2:51 PM
15   3:51 PM
16   4:51 PM
17   5:51 PM
18   6:51 PM
19   7:51 PM
20   8:51 PM
21   9:51 PM
22  10:51 PM
23  11:51 PM

In [11]:
print(df.iloc[0,1])

30.9

In [12]:
print(df.iloc[0,4])

30.35

In [13]:
print(df.iloc[0:4,4:5])

   Sea Level PressureIn
0                 30.35
1                 30.35
2                 30.33
3                 30.31

In [14]:
print(df)

     TimeEST  TemperatureF  Dew PointF  Humidity  Sea Level PressureIn  \
0   12:51 AM          30.9        27.0        85                 30.35
1    1:51 AM          30.0        26.1        85                 30.35
2    2:51 AM          28.9        25.0        85                 30.33
3    3:51 AM          33.1        26.1        75                 30.31
4    4:51 AM          30.9        26.1        82                 30.32
5    5:51 AM          32.0        26.1        79                 30.30
6    6:51 AM          28.9        26.1        89                 30.31
7    7:51 AM          33.1        28.0        82                 30.34
8    8:51 AM          37.9        30.0        73                 30.34
9    9:51 AM          41.0        32.0        70                 30.33
10  10:51 AM          46.0        30.9        56                 30.30
11  11:51 AM          46.9        30.0        52                 30.27
12  12:51 PM          53.1        35.1        50                 30.19
13   1:51 PM          55.0        39.0        55                 30.15
14   2:51 PM          57.0        41.0        55                 30.11
15   3:51 PM          55.9        41.0        57                 30.08
16   4:51 PM          57.0        43.0        59                 30.04
17   5:51 PM          55.9        44.1        64                 30.02
18   6:51 PM          54.0        44.1        69                 30.01
19   7:51 PM          52.0        44.1        74                 30.03
20   8:51 PM          51.1        44.1        77                 30.02
21   9:51 PM          48.0        42.1        80                 30.02
22  10:51 PM          46.9        42.1        83                 30.01
23  11:51 PM          46.0        41.0        83                 30.00

    VisibilityMPH Wind Direction Wind SpeedMPH Gust SpeedMPH  PrecipitationIn  \
0              10           Calm          Calm             -              NaN
1              10           Calm          Calm             -              NaN
2              10           Calm          Calm             -              NaN
3              10            ESE           5.8             -              NaN
4              10           Calm          Calm             -              NaN
5              10             SE           4.6             -              NaN
6              10           Calm          Calm             -              NaN
7              10            SSW           4.6             -              NaN
8              10            SSW           4.6             -              NaN
9              10             SE           5.8             -              NaN
10             10            SSW           5.8             -              NaN
11             10            SSW          10.4             -              NaN
12             10          South           9.2             -              NaN
13             10             SW            15             -              NaN
14             10            SSW          12.7          18.4              NaN
15             10            SSW          11.5             -              NaN
16             10            SSW          13.8             -              NaN
17             10            SSW          16.1             -              NaN
18             10            SSW            15             -              NaN
19             10             SW           8.1             -              NaN
20             10             SW          10.4             -              NaN
21             10             SW           5.8             -              NaN
22             10             SW           6.9             -              NaN
23             10             SW           5.8             -              NaN

    Events        Conditions  WindDirDegrees           DateUTC
0      NaN     Partly Cloudy               0  21-02-2012 05:51
1      NaN     Partly Cloudy               0  21-02-2012 06:51
2      NaN  Scattered Clouds               0  21-02-2012 07:51
3      NaN  Scattered Clouds             120  21-02-2012 08:51
4      NaN  Scattered Clouds               0  21-02-2012 09:51
5      NaN  Scattered Clouds             130  21-02-2012 10:51
6      NaN     Mostly Cloudy               0  21-02-2012 11:51
7      NaN     Mostly Cloudy             200  21-02-2012 12:51
8      NaN     Mostly Cloudy             200  21-02-2012 13:51
9      NaN     Mostly Cloudy             140  21-02-2012 14:51
10     NaN     Mostly Cloudy             200  21-02-2012 15:51
11     NaN     Mostly Cloudy             210  21-02-2012 16:51
12     NaN     Mostly Cloudy             190  21-02-2012 17:51
13     NaN     Mostly Cloudy             220  21-02-2012 18:51
14     NaN     Mostly Cloudy             200  21-02-2012 19:51
15     NaN     Mostly Cloudy             210  21-02-2012 20:51
16     NaN     Mostly Cloudy             210  21-02-2012 21:51
17     NaN     Mostly Cloudy             210  21-02-2012 22:51
18     NaN     Mostly Cloudy             210  21-02-2012 23:51
19     NaN     Mostly Cloudy             230  22-02-2012 00:51
20     NaN     Partly Cloudy             220  22-02-2012 01:51
21     NaN     Partly Cloudy             230  22-02-2012 02:51
22     NaN     Partly Cloudy             230  22-02-2012 03:51
23     NaN             Clear             230  22-02-2012 04:51

In [15]:
df

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51

In [16]:
print(df.iloc[[0,2,3],[4,5]])

   Sea Level PressureIn  VisibilityMPH
0                 30.35             10
2                 30.33             10
3                 30.31             10

In [17]:
#get specific column
import pandas as pd
df1=pd.read_csv("weather_1.csv",skipinitialspace=True)
df1

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51

In [18]:
df2=df1.values.tolist()
df2

[['12:51 AM',
  30.9,
  27.0,
  85,
  30.35,
  10,
  'Calm',
  'Calm',
  '-',
  nan,
  nan,
  'Partly Cloudy',
  0,
  '21-02-2012 05:51'],
 ['1:51 AM',
  30.0,
  26.1,
  85,
  30.35,
  10,
  'Calm',
  'Calm',
  '-',
  nan,
  nan,
  'Partly Cloudy',
  0,
  '21-02-2012 06:51'],
 ['2:51 AM',
  28.9,
  25.0,
  85,
  30.33,
  10,
  'Calm',
  'Calm',
  '-',
  nan,
  nan,
  'Scattered Clouds',
  0,
  '21-02-2012 07:51'],
 ['3:51 AM',
  33.1,
  26.1,
  75,
  30.31,
  10,
  'ESE',
  '5.8',
  '-',
  nan,
  nan,
  'Scattered Clouds',
  120,
  '21-02-2012 08:51'],
 ['4:51 AM',
  30.9,
  26.1,
  82,
  30.32,
  10,
  'Calm',
  'Calm',
  '-',
  nan,
  nan,
  'Scattered Clouds',
  0,
  '21-02-2012 09:51'],
 ['5:51 AM',
  32.0,
  26.1,
  79,
  30.3,
  10,
  'SE',
  '4.6',
  '-',
  nan,
  nan,
  'Scattered Clouds',
  130,
  '21-02-2012 10:51'],
 ['6:51 AM',
  28.9,
  26.1,
  89,
  30.31,
  10,
  'Calm',
  'Calm',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  0,
  '21-02-2012 11:51'],
 ['7:51 AM',
  33.1,
  28.0,
  82,
  30.34,
  10,
  'SSW',
  '4.6',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  200,
  '21-02-2012 12:51'],
 ['8:51 AM',
  37.9,
  30.0,
  73,
  30.34,
  10,
  'SSW',
  '4.6',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  200,
  '21-02-2012 13:51'],
 ['9:51 AM',
  41.0,
  32.0,
  70,
  30.33,
  10,
  'SE',
  '5.8',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  140,
  '21-02-2012 14:51'],
 ['10:51 AM',
  46.0,
  30.9,
  56,
  30.3,
  10,
  'SSW',
  '5.8',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  200,
  '21-02-2012 15:51'],
 ['11:51 AM',
  46.9,
  30.0,
  52,
  30.27,
  10,
  'SSW',
  '10.4',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  210,
  '21-02-2012 16:51'],
 ['12:51 PM',
  53.1,
  35.1,
  50,
  30.19,
  10,
  'South',
  '9.2',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  190,
  '21-02-2012 17:51'],
 ['1:51 PM',
  55.0,
  39.0,
  55,
  30.15,
  10,
  'SW',
  '15',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  220,
  '21-02-2012 18:51'],
 ['2:51 PM',
  57.0,
  41.0,
  55,
  30.11,
  10,
  'SSW',
  '12.7',
  '18.4',
  nan,
  nan,
  'Mostly Cloudy',
  200,
  '21-02-2012 19:51'],
 ['3:51 PM',
  55.9,
  41.0,
  57,
  30.08,
  10,
  'SSW',
  '11.5',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  210,
  '21-02-2012 20:51'],
 ['4:51 PM',
  57.0,
  43.0,
  59,
  30.04,
  10,
  'SSW',
  '13.8',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  210,
  '21-02-2012 21:51'],
 ['5:51 PM',
  55.9,
  44.1,
  64,
  30.02,
  10,
  'SSW',
  '16.1',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  210,
  '21-02-2012 22:51'],
 ['6:51 PM',
  54.0,
  44.1,
  69,
  30.01,
  10,
  'SSW',
  '15',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  210,
  '21-02-2012 23:51'],
 ['7:51 PM',
  52.0,
  44.1,
  74,
  30.03,
  10,
  'SW',
  '8.1',
  '-',
  nan,
  nan,
  'Mostly Cloudy',
  230,
  '22-02-2012 00:51'],
 ['8:51 PM',
  51.1,
  44.1,
  77,
  30.02,
  10,
  'SW',
  '10.4',
  '-',
  nan,
  nan,
  'Partly Cloudy',
  220,
  '22-02-2012 01:51'],
 ['9:51 PM',
  48.0,
  42.1,
  80,
  30.02,
  10,
  'SW',
  '5.8',
  '-',
  nan,
  nan,
  'Partly Cloudy',
  230,
  '22-02-2012 02:51'],
 ['10:51 PM',
  46.9,
  42.1,
  83,
  30.01,
  10,
  'SW',
  '6.9',
  '-',
  nan,
  nan,
  'Partly Cloudy',
  230,
  '22-02-2012 03:51'],
 ['11:51 PM',
  46.0,
  41.0,
  83,
  30.0,
  10,
  'SW',
  '5.8',
  '-',
  nan,
  nan,
  'Clear',
  230,
  '22-02-2012 04:51']]

In [19]:
df2=df1["TimeEST"].tolist()
df2

['12:51 AM',
 '1:51 AM',
 '2:51 AM',
 '3:51 AM',
 '4:51 AM',
 '5:51 AM',
 '6:51 AM',
 '7:51 AM',
 '8:51 AM',
 '9:51 AM',
 '10:51 AM',
 '11:51 AM',
 '12:51 PM',
 '1:51 PM',
 '2:51 PM',
 '3:51 PM',
 '4:51 PM',
 '5:51 PM',
 '6:51 PM',
 '7:51 PM',
 '8:51 PM',
 '9:51 PM',
 '10:51 PM',
 '11:51 PM']

In [20]:
df2=df1["Wind SpeedMPH"].tolist()
df2

['Calm',
 'Calm',
 'Calm',
 '5.8',
 'Calm',
 '4.6',
 'Calm',
 '4.6',
 '4.6',
 '5.8',
 '5.8',
 '10.4',
 '9.2',
 '15',
 '12.7',
 '11.5',
 '13.8',
 '16.1',
 '15',
 '8.1',
 '10.4',
 '5.8',
 '6.9',
 '5.8']

In [21]:
df2=df1.loc[:,"TimeEST"].tolist()
df2

['12:51 AM',
 '1:51 AM',
 '2:51 AM',
 '3:51 AM',
 '4:51 AM',
 '5:51 AM',
 '6:51 AM',
 '7:51 AM',
 '8:51 AM',
 '9:51 AM',
 '10:51 AM',
 '11:51 AM',
 '12:51 PM',
 '1:51 PM',
 '2:51 PM',
 '3:51 PM',
 '4:51 PM',
 '5:51 PM',
 '6:51 PM',
 '7:51 PM',
 '8:51 PM',
 '9:51 PM',
 '10:51 PM',
 '11:51 PM']

In [22]:
df2=df1.loc[:,"TimeEST"].tolist()
df2

['12:51 AM',
 '1:51 AM',
 '2:51 AM',
 '3:51 AM',
 '4:51 AM',
 '5:51 AM',
 '6:51 AM',
 '7:51 AM',
 '8:51 AM',
 '9:51 AM',
 '10:51 AM',
 '11:51 AM',
 '12:51 PM',
 '1:51 PM',
 '2:51 PM',
 '3:51 PM',
 '4:51 PM',
 '5:51 PM',
 '6:51 PM',
 '7:51 PM',
 '8:51 PM',
 '9:51 PM',
 '10:51 PM',
 '11:51 PM']

In [23]:
#sort by index

sdf=df1.sort_index()
sdf

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51

In [24]:
sdf=df1.sort_index(ascending=True)
sdf

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51

In [25]:
sdf=df1.sort_index(axis=1)
sdf

,Conditions,DateUTC,Dew PointF,Events,Gust SpeedMPH,Humidity,PrecipitationIn,Sea Level PressureIn,TemperatureF,TimeEST,VisibilityMPH,Wind Direction,Wind SpeedMPH,WindDirDegrees
0,Partly Cloudy,21-02-2012 05:51,27.0,NaN,-,85,NaN,30.35,30.9,12:51 AM,10,Calm,Calm,0
1,Partly Cloudy,21-02-2012 06:51,26.1,NaN,-,85,NaN,30.35,30.0,1:51 AM,10,Calm,Calm,0
2,Scattered Clouds,21-02-2012 07:51,25.0,NaN,-,85,NaN,30.33,28.9,2:51 AM,10,Calm,Calm,0
3,Scattered Clouds,21-02-2012 08:51,26.1,NaN,-,75,NaN,30.31,33.1,3:51 AM,10,ESE,5.8,120
4,Scattered Clouds,21-02-2012 09:51,26.1,NaN,-,82,NaN,30.32,30.9,4:51 AM,10,Calm,Calm,0
5,Scattered Clouds,21-02-2012 10:51,26.1,NaN,-,79,NaN,30.30,32.0,5:51 AM,10,SE,4.6,130
6,Mostly Cloudy,21-02-2012 11:51,26.1,NaN,-,89,NaN,30.31,28.9,6:51 AM,10,Calm,Calm,0
7,Mostly Cloudy,21-02-2012 12:51,28.0,NaN,-,82,NaN,30.34,33.1,7:51 AM,10,SSW,4.6,200
8,Mostly Cloudy,21-02-2012 13:51,30.0,NaN,-,73,NaN,30.34,37.9,8:51 AM,10,SSW,4.6,200
9,Mostly Cloudy,21-02-2012 14:51,32.0,NaN,-,70,NaN,30.33,41.0,9:51 AM,10,SE,5.8,140
10,Mostly Cloudy,21-02-2012 15:51,30.9,NaN,-,56,NaN,30.30,46.0,10:51 AM,10,SSW,5.8,200
11,Mostly Cloudy,21-02-2012 16:51,30.0,NaN,-,52,NaN,30.27,46.9,11:51 AM,10,SSW,10.4,210
12,Mostly Cloudy,21-02-2012 17:51,35.1,NaN,-,50,NaN,30.19,53.1,12:51 PM,10,South,9.2,190
13,Mostly Cloudy,21-02-2012 18:51,39.0,NaN,-,55,NaN,30.15,55.0,1:51 PM,10,SW,15,220
14,Mostly Cloudy,21-02-2012 19:51,41.0,NaN,18.4,55,NaN,30.11,57.0,2:51 PM,10,SSW,12.7,200
15,Mostly Cloudy,21-02-2012 20:51,41.0,NaN,-,57,NaN,30.08,55.9,3:51 PM,10,SSW,11.5,210
16,Mostly Cloudy,21-02-2012 21:51,43.0,NaN,-,59,NaN,30.04,57.0,4:51 PM,10,SSW,13.8,210
17,Mostly Cloudy,21-02-2012 22:51,44.1,NaN,-,64,NaN,30.02,55.9,5:51 PM,10,SSW,16.1,210
18,Mostly Cloudy,21-02-2012 23:51,44.1,NaN,-,69,NaN,30.01,54.0,6:51 PM,10,SSW,15,210
19,Mostly Cloudy,22-02-2012 00:51,44.1,NaN,-,74,NaN,30.03,52.0,7:51 PM,10,SW,8.1,230
20,Partly Cloudy,22-02-2012 01:51,44.1,NaN,-,77,NaN,30.02,51.1,8:51 PM,10,SW,10.4,220
21,Partly Cloudy,22-02-2012 02:51,42.1,NaN,-,80,NaN,30.02,48.0,9:51 PM,10,SW,5.8,230
22,Partly Cloudy,22-02-2012 03:51,42.1,NaN,-,83,NaN,30.01,46.9,10:51 PM,10,SW,6.9,230
23,Clear,22-02-2012 04:51,41.0,NaN,-,83,NaN,30.00,46.0,11:51 PM,10,SW,5.8,230

In [26]:
sdf=df1.sort_index(axis=1,ascending=False)
sdf

,WindDirDegrees,Wind SpeedMPH,Wind Direction,VisibilityMPH,TimeEST,TemperatureF,Sea Level PressureIn,PrecipitationIn,Humidity,Gust SpeedMPH,Events,Dew PointF,DateUTC,Conditions
0,0,Calm,Calm,10,12:51 AM,30.9,30.35,NaN,85,-,NaN,27.0,21-02-2012 05:51,Partly Cloudy
1,0,Calm,Calm,10,1:51 AM,30.0,30.35,NaN,85,-,NaN,26.1,21-02-2012 06:51,Partly Cloudy
2,0,Calm,Calm,10,2:51 AM,28.9,30.33,NaN,85,-,NaN,25.0,21-02-2012 07:51,Scattered Clouds
3,120,5.8,ESE,10,3:51 AM,33.1,30.31,NaN,75,-,NaN,26.1,21-02-2012 08:51,Scattered Clouds
4,0,Calm,Calm,10,4:51 AM,30.9,30.32,NaN,82,-,NaN,26.1,21-02-2012 09:51,Scattered Clouds
5,130,4.6,SE,10,5:51 AM,32.0,30.30,NaN,79,-,NaN,26.1,21-02-2012 10:51,Scattered Clouds
6,0,Calm,Calm,10,6:51 AM,28.9,30.31,NaN,89,-,NaN,26.1,21-02-2012 11:51,Mostly Cloudy
7,200,4.6,SSW,10,7:51 AM,33.1,30.34,NaN,82,-,NaN,28.0,21-02-2012 12:51,Mostly Cloudy
8,200,4.6,SSW,10,8:51 AM,37.9,30.34,NaN,73,-,NaN,30.0,21-02-2012 13:51,Mostly Cloudy
9,140,5.8,SE,10,9:51 AM,41.0,30.33,NaN,70,-,NaN,32.0,21-02-2012 14:51,Mostly Cloudy
10,200,5.8,SSW,10,10:51 AM,46.0,30.30,NaN,56,-,NaN,30.9,21-02-2012 15:51,Mostly Cloudy
11,210,10.4,SSW,10,11:51 AM,46.9,30.27,NaN,52,-,NaN,30.0,21-02-2012 16:51,Mostly Cloudy
12,190,9.2,South,10,12:51 PM,53.1,30.19,NaN,50,-,NaN,35.1,21-02-2012 17:51,Mostly Cloudy
13,220,15,SW,10,1:51 PM,55.0,30.15,NaN,55,-,NaN,39.0,21-02-2012 18:51,Mostly Cloudy
14,200,12.7,SSW,10,2:51 PM,57.0,30.11,NaN,55,18.4,NaN,41.0,21-02-2012 19:51,Mostly Cloudy
15,210,11.5,SSW,10,3:51 PM,55.9,30.08,NaN,57,-,NaN,41.0,21-02-2012 20:51,Mostly Cloudy
16,210,13.8,SSW,10,4:51 PM,57.0,30.04,NaN,59,-,NaN,43.0,21-02-2012 21:51,Mostly Cloudy
17,210,16.1,SSW,10,5:51 PM,55.9,30.02,NaN,64,-,NaN,44.1,21-02-2012 22:51,Mostly Cloudy
18,210,15,SSW,10,6:51 PM,54.0,30.01,NaN,69,-,NaN,44.1,21-02-2012 23:51,Mostly Cloudy
19,230,8.1,SW,10,7:51 PM,52.0,30.03,NaN,74,-,NaN,44.1,22-02-2012 00:51,Mostly Cloudy
20,220,10.4,SW,10,8:51 PM,51.1,30.02,NaN,77,-,NaN,44.1,22-02-2012 01:51,Partly Cloudy
21,230,5.8,SW,10,9:51 PM,48.0,30.02,NaN,80,-,NaN,42.1,22-02-2012 02:51,Partly Cloudy
22,230,6.9,SW,10,10:51 PM,46.9,30.01,NaN,83,-,NaN,42.1,22-02-2012 03:51,Partly Cloudy
23,230,5.8,SW,10,11:51 PM,46.0,30.00,NaN,83,-,NaN,41.0,22-02-2012 04:51,Clear

In [27]:
#sort by values

df=df1.sort_values(by="TemperatureF")
df

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51

In [28]:
df=df1.sort_values("TemperatureF")
df

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51

In [29]:
df=df1.sort_values("TemperatureF",ascending=False)
df

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51

In [30]:
df=df1.sort_values(by=["TemperatureF","TemperatureF"])
df

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51

In [31]:
#zip(map the value)
name=["ek","do","tin"]
roll_no=[1,2,3]
mapped=zip(name,roll_no)
print(list(mapped))

[('ek', 1), ('do', 2), ('tin', 3)]

In [32]:
import pandas as pd
df=pd.read_csv("weather_1.csv")
print(list(zip(df["TemperatureF"],df["Humidity"])))

[(30.9, 85), (30.0, 85), (28.9, 85), (33.1, 75), (30.9, 82), (32.0, 79), (28.9, 89), (33.1, 82), (37.9, 73), (41.0, 70), (46.0, 56), (46.9, 52), (53.1, 50), (55.0, 55), (57.0, 55), (55.9, 57), (57.0, 59), (55.9, 64), (54.0, 69), (52.0, 74), (51.1, 77), (48.0, 80), (46.9, 83), (46.0, 83)]

In [33]:
print(list(zip(*df.values)))

[('12:51 AM', '1:51 AM', '2:51 AM', '3:51 AM', '4:51 AM', '5:51 AM', '6:51 AM', '7:51 AM', '8:51 AM', '9:51 AM', '10:51 AM', '11:51 AM', '12:51 PM', '1:51 PM', '2:51 PM', '3:51 PM', '4:51 PM', '5:51 PM', '6:51 PM', '7:51 PM', '8:51 PM', '9:51 PM', '10:51 PM', '11:51 PM'), (30.9, 30.0, 28.9, 33.1, 30.9, 32.0, 28.9, 33.1, 37.9, 41.0, 46.0, 46.9, 53.1, 55.0, 57.0, 55.9, 57.0, 55.9, 54.0, 52.0, 51.1, 48.0, 46.9, 46.0), (27.0, 26.1, 25.0, 26.1, 26.1, 26.1, 26.1, 28.0, 30.0, 32.0, 30.9, 30.0, 35.1, 39.0, 41.0, 41.0, 43.0, 44.1, 44.1, 44.1, 44.1, 42.1, 42.1, 41.0), (85, 85, 85, 75, 82, 79, 89, 82, 73, 70, 56, 52, 50, 55, 55, 57, 59, 64, 69, 74, 77, 80, 83, 83), (30.35, 30.35, 30.33, 30.31, 30.32, 30.3, 30.31, 30.34, 30.34, 30.33, 30.3, 30.27, 30.19, 30.15, 30.11, 30.08, 30.04, 30.02, 30.01, 30.03, 30.02, 30.02, 30.01, 30.0), (10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10), ('Calm', 'Calm', 'Calm', 'ESE', 'Calm', 'SE', 'Calm', 'SSW', 'SSW', 'SE', 'SSW', 'SSW', 'South', 'SW', 'SSW', 'SSW', 'SSW', 'SSW', 'SSW', 'SW', 'SW', 'SW', 'SW', 'SW'), ('Calm', 'Calm', 'Calm', '5.8', 'Calm', '4.6', 'Calm', '4.6', '4.6', '5.8', '5.8', '10.4', '9.2', '15', '12.7', '11.5', '13.8', '16.1', '15', '8.1', '10.4', '5.8', '6.9', '5.8'), ('-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '18.4', '-', '-', '-', '-', '-', '-', '-', '-', '-'), (nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan), (nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan), ('Partly Cloudy', 'Partly Cloudy', 'Scattered Clouds', 'Scattered Clouds', 'Scattered Clouds', 'Scattered Clouds', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Partly Cloudy', 'Partly Cloudy', 'Partly Cloudy', 'Clear'), (0, 0, 0, 120, 0, 130, 0, 200, 200, 140, 200, 210, 190, 220, 200, 210, 210, 210, 210, 230, 220, 230, 230, 230), ('21-02-2012 05:51', '21-02-2012 06:51', '21-02-2012 07:51', '21-02-2012 08:51', '21-02-2012 09:51', '21-02-2012 10:51', '21-02-2012 11:51', '21-02-2012 12:51', '21-02-2012 13:51', '21-02-2012 14:51', '21-02-2012 15:51', '21-02-2012 16:51', '21-02-2012 17:51', '21-02-2012 18:51', '21-02-2012 19:51', '21-02-2012 20:51', '21-02-2012 21:51', '21-02-2012 22:51', '21-02-2012 23:51', '22-02-2012 00:51', '22-02-2012 01:51', '22-02-2012 02:51', '22-02-2012 03:51', '22-02-2012 04:51')]

In [34]:
#filtering data
#provide query() method
df=pd.read_csv("weather_1.csv")
df

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51

In [35]:
df.columns=[column.replace(" ","_") for column in df.columns]
df

,TimeEST,TemperatureF,Dew_PointF,Humidity,Sea_Level_PressureIn,VisibilityMPH,Wind_Direction,Wind_SpeedMPH,Gust_SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51

In [36]:
df.query('Dew_PointF==44.1',inplace=True)
df

,TimeEST,TemperatureF,Dew_PointF,Humidity,Sea_Level_PressureIn,VisibilityMPH,Wind_Direction,Wind_SpeedMPH,Gust_SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51

In [37]:
df.query('Wind_Direction=="SSW" and VisibilityMPH > 8.1',inplace=True)
df

,TimeEST,TemperatureF,Dew_PointF,Humidity,Sea_Level_PressureIn,VisibilityMPH,Wind_Direction,Wind_SpeedMPH,Gust_SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51

In [38]:
df=pd.read_csv("weather_1.csv")
df

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
2,2:51 AM,28.9,25.0,85,30.33,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 07:51
3,3:51 AM,33.1,26.1,75,30.31,10,ESE,5.8,-,NaN,NaN,Scattered Clouds,120,21-02-2012 08:51
4,4:51 AM,30.9,26.1,82,30.32,10,Calm,Calm,-,NaN,NaN,Scattered Clouds,0,21-02-2012 09:51
5,5:51 AM,32.0,26.1,79,30.30,10,SE,4.6,-,NaN,NaN,Scattered Clouds,130,21-02-2012 10:51
6,6:51 AM,28.9,26.1,89,30.31,10,Calm,Calm,-,NaN,NaN,Mostly Cloudy,0,21-02-2012 11:51
7,7:51 AM,33.1,28.0,82,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 12:51
8,8:51 AM,37.9,30.0,73,30.34,10,SSW,4.6,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 13:51
9,9:51 AM,41.0,32.0,70,30.33,10,SE,5.8,-,NaN,NaN,Mostly Cloudy,140,21-02-2012 14:51
10,10:51 AM,46.0,30.9,56,30.30,10,SSW,5.8,-,NaN,NaN,Mostly Cloudy,200,21-02-2012 15:51
11,11:51 AM,46.9,30.0,52,30.27,10,SSW,10.4,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 16:51
12,12:51 PM,53.1,35.1,50,30.19,10,South,9.2,-,NaN,NaN,Mostly Cloudy,190,21-02-2012 17:51
13,1:51 PM,55.0,39.0,55,30.15,10,SW,15,-,NaN,NaN,Mostly Cloudy,220,21-02-2012 18:51
14,2:51 PM,57.0,41.0,55,30.11,10,SSW,12.7,18.4,NaN,NaN,Mostly Cloudy,200,21-02-2012 19:51
15,3:51 PM,55.9,41.0,57,30.08,10,SSW,11.5,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 20:51
16,4:51 PM,57.0,43.0,59,30.04,10,SSW,13.8,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 21:51
17,5:51 PM,55.9,44.1,64,30.02,10,SSW,16.1,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 22:51
18,6:51 PM,54.0,44.1,69,30.01,10,SSW,15,-,NaN,NaN,Mostly Cloudy,210,21-02-2012 23:51
19,7:51 PM,52.0,44.1,74,30.03,10,SW,8.1,-,NaN,NaN,Mostly Cloudy,230,22-02-2012 00:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51
23,11:51 PM,46.0,41.0,83,30.00,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51

In [39]:
df.loc[df["Conditions"].str.contains("Clear")]

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
23,11:51 PM,46.0,41.0,83,30.0,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51

In [40]:
df.loc[df["Conditions"].str.startswith("P")]

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
0,12:51 AM,30.9,27.0,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 05:51
1,1:51 AM,30.0,26.1,85,30.35,10,Calm,Calm,-,NaN,NaN,Partly Cloudy,0,21-02-2012 06:51
20,8:51 PM,51.1,44.1,77,30.02,10,SW,10.4,-,NaN,NaN,Partly Cloudy,220,22-02-2012 01:51
21,9:51 PM,48.0,42.1,80,30.02,10,SW,5.8,-,NaN,NaN,Partly Cloudy,230,22-02-2012 02:51
22,10:51 PM,46.9,42.1,83,30.01,10,SW,6.9,-,NaN,NaN,Partly Cloudy,230,22-02-2012 03:51

In [41]:
df.loc[df["Conditions"].str.endswith("r")]

,TimeEST,TemperatureF,Dew PointF,Humidity,Sea Level PressureIn,VisibilityMPH,Wind Direction,Wind SpeedMPH,Gust SpeedMPH,PrecipitationIn,Events,Conditions,WindDirDegrees,DateUTC
23,11:51 PM,46.0,41.0,83,30.0,10,SW,5.8,-,NaN,NaN,Clear,230,22-02-2012 04:51

In [42]:
#excelfile operation
import pandas as pd
df=pd.read_excel("Aug_2022.xlsx")
df

,Days,Time,Max T,Min T,Dry T,Wet T,Hum,Press,Wind D.,Wind St,Cl am,Cl Ty,Rain,Snow
0,1,9,26.43,11.78,18.97,16.22,76,1023.9,S,1,0,C.,1.00,0
1,2,9,26.18,18.20,21.54,19.38,82,1016.7,SW,2,8,Sc.,0.40,0
2,3,9,26.45,17.86,20.23,18.59,85,1016.0,WNW,2,6,Cu.,0.00,0
3,4,9,21.70,12.89,18.31,15.38,74,1020.0,NW,3,4,Cu.,0.00,0
4,5,9,20.79,10.02,15.38,13.45,81,1027.4,NW,3,4,Cu.,0.00,0
5,6,9,23.54,7.32,17.81,15.06,75,1034.9,NNW,2,3,Cu.,0.00,0
6,7,9,25.51,9.02,12.29,10.72,83,1031.9,NW,2,1,Ci.,0.00,0
7,8,9,28.49,11.47,20.51,17.57,75,1032.9,NNE,1,1,Cu.,0.00,0
8,9,9,29.43,12.41,19.03,16.16,78,1034.6,N,1,1,Ci.,0.00,0
9,10,9,31.57,13.27,24.25,20.95,74,1030.9,S,1,0,C.,0.00,0
10,11,9,33.09,13.30,24.20,20.56,71,1027.9,E,1,0,C.,0.00,0
11,12,9,33.25,14.10,26.49,23.76,80,1024.9,NE,2,0,C.,0.00,0
12,13,9,33.23,15.27,22.48,19.72,77,1021.2,NE,2,0,C.,0.00,0
13,14,9,33.30,15.98,24.40,21.28,76,1013.2,NE,1,1,As.,0.00,0
14,15,9,26.31,16.16,21.44,18.67,77,1006.6,NW,2,6,Sc.,0.00,0
15,16,9,23.16,15.37,18.98,16.61,81,1012.1,N,2,7,As.,1.50,0
16,17,9,17.75,14.80,14.81,14.14,93,1019.5,NNE,3,8,Sc.,0.00,0
17,18,9,24.08,15.30,18.03,16.65,87,1019.1,S,1,7,Sc.,0.00,0
18,19,9,21.85,14.32,17.61,15.49,80,1018.7,WNW,2,1,Cu.,0.00,0
19,20,9,24.56,12.13,19.73,17.19,78,1020.4,WSW,22,6,Cu.,0.00,0
20,21,9,23.04,13.38,19.41,16.99,78,1019.2,W,1,3,Cu.,0.00,0
21,22,9,24.64,12.10,19.40,15.67,67,1017.9,SSW,2,7,Cu.,1.50,0
22,23,9,25.18,17.90,22.04,18.61,72,1017.2,SSW,2,6,Cu.,0.00,0
23,24,9,24.39,19.31,20.79,18.45,80,1019.7,SW,2,8,Cc.,5.00,0
24,25,9,20.73,15.70,15.78,15.26,94,1023.6,NW,2,8,Sc.,2.50,0
25,26,9,23.59,10.47,17.00,13.67,69,1024.9,NW,1,2,Cu.,0.25,0
26,27,9,24.91,12.98,17.40,15.57,83,1025.0,NE,2,2,Cu.,0.00,0
27,28,9,24.11,11.45,17.17,15.11,80,1027.8,SSE,2,2,Ci.,0.00,0
28,29,9,20.34,14.56,18.13,15.08,72,1029.6,NE,3,7,Sc.,0.25,0
29,30,9,22.76,10.40,15.03,12.31,73,1030.7,NE,3,2,Ci.,0.00,0
30,31,9,22.99,12.17,15.58,14.01,84,1031.9,NE,3,8,Sc.,0.00,0

In [43]:
df.columns=[column.replace(" ","_") for column in df.columns]
df

,Days,Time,Max_T,Min_T,Dry_T,Wet_T,Hum,Press,Wind_D.,Wind_St,Cl_am,Cl_Ty,Rain,Snow
0,1,9,26.43,11.78,18.97,16.22,76,1023.9,S,1,0,C.,1.00,0
1,2,9,26.18,18.20,21.54,19.38,82,1016.7,SW,2,8,Sc.,0.40,0
2,3,9,26.45,17.86,20.23,18.59,85,1016.0,WNW,2,6,Cu.,0.00,0
3,4,9,21.70,12.89,18.31,15.38,74,1020.0,NW,3,4,Cu.,0.00,0
4,5,9,20.79,10.02,15.38,13.45,81,1027.4,NW,3,4,Cu.,0.00,0
5,6,9,23.54,7.32,17.81,15.06,75,1034.9,NNW,2,3,Cu.,0.00,0
6,7,9,25.51,9.02,12.29,10.72,83,1031.9,NW,2,1,Ci.,0.00,0
7,8,9,28.49,11.47,20.51,17.57,75,1032.9,NNE,1,1,Cu.,0.00,0
8,9,9,29.43,12.41,19.03,16.16,78,1034.6,N,1,1,Ci.,0.00,0
9,10,9,31.57,13.27,24.25,20.95,74,1030.9,S,1,0,C.,0.00,0
10,11,9,33.09,13.30,24.20,20.56,71,1027.9,E,1,0,C.,0.00,0
11,12,9,33.25,14.10,26.49,23.76,80,1024.9,NE,2,0,C.,0.00,0
12,13,9,33.23,15.27,22.48,19.72,77,1021.2,NE,2,0,C.,0.00,0
13,14,9,33.30,15.98,24.40,21.28,76,1013.2,NE,1,1,As.,0.00,0
14,15,9,26.31,16.16,21.44,18.67,77,1006.6,NW,2,6,Sc.,0.00,0
15,16,9,23.16,15.37,18.98,16.61,81,1012.1,N,2,7,As.,1.50,0
16,17,9,17.75,14.80,14.81,14.14,93,1019.5,NNE,3,8,Sc.,0.00,0
17,18,9,24.08,15.30,18.03,16.65,87,1019.1,S,1,7,Sc.,0.00,0
18,19,9,21.85,14.32,17.61,15.49,80,1018.7,WNW,2,1,Cu.,0.00,0
19,20,9,24.56,12.13,19.73,17.19,78,1020.4,WSW,22,6,Cu.,0.00,0
20,21,9,23.04,13.38,19.41,16.99,78,1019.2,W,1,3,Cu.,0.00,0
21,22,9,24.64,12.10,19.40,15.67,67,1017.9,SSW,2,7,Cu.,1.50,0
22,23,9,25.18,17.90,22.04,18.61,72,1017.2,SSW,2,6,Cu.,0.00,0
23,24,9,24.39,19.31,20.79,18.45,80,1019.7,SW,2,8,Cc.,5.00,0
24,25,9,20.73,15.70,15.78,15.26,94,1023.6,NW,2,8,Sc.,2.50,0
25,26,9,23.59,10.47,17.00,13.67,69,1024.9,NW,1,2,Cu.,0.25,0
26,27,9,24.91,12.98,17.40,15.57,83,1025.0,NE,2,2,Cu.,0.00,0
27,28,9,24.11,11.45,17.17,15.11,80,1027.8,SSE,2,2,Ci.,0.00,0
28,29,9,20.34,14.56,18.13,15.08,72,1029.6,NE,3,7,Sc.,0.25,0
29,30,9,22.76,10.40,15.03,12.31,73,1030.7,NE,3,2,Ci.,0.00,0
30,31,9,22.99,12.17,15.58,14.01,84,1031.9,NE,3,8,Sc.,0.00,0

In [44]:
df.loc[df["Max_T"]>30.0]

,Days,Time,Max_T,Min_T,Dry_T,Wet_T,Hum,Press,Wind_D.,Wind_St,Cl_am,Cl_Ty,Rain,Snow
9,10,9,31.57,13.27,24.25,20.95,74,1030.9,S,1,0,C.,0.0,0
10,11,9,33.09,13.30,24.20,20.56,71,1027.9,E,1,0,C.,0.0,0
11,12,9,33.25,14.10,26.49,23.76,80,1024.9,NE,2,0,C.,0.0,0
12,13,9,33.23,15.27,22.48,19.72,77,1021.2,NE,2,0,C.,0.0,0
13,14,9,33.30,15.98,24.40,21.28,76,1013.2,NE,1,1,As.,0.0,0

In [45]:
df

,Days,Time,Max_T,Min_T,Dry_T,Wet_T,Hum,Press,Wind_D.,Wind_St,Cl_am,Cl_Ty,Rain,Snow
0,1,9,26.43,11.78,18.97,16.22,76,1023.9,S,1,0,C.,1.00,0
1,2,9,26.18,18.20,21.54,19.38,82,1016.7,SW,2,8,Sc.,0.40,0
2,3,9,26.45,17.86,20.23,18.59,85,1016.0,WNW,2,6,Cu.,0.00,0
3,4,9,21.70,12.89,18.31,15.38,74,1020.0,NW,3,4,Cu.,0.00,0
4,5,9,20.79,10.02,15.38,13.45,81,1027.4,NW,3,4,Cu.,0.00,0
5,6,9,23.54,7.32,17.81,15.06,75,1034.9,NNW,2,3,Cu.,0.00,0
6,7,9,25.51,9.02,12.29,10.72,83,1031.9,NW,2,1,Ci.,0.00,0
7,8,9,28.49,11.47,20.51,17.57,75,1032.9,NNE,1,1,Cu.,0.00,0
8,9,9,29.43,12.41,19.03,16.16,78,1034.6,N,1,1,Ci.,0.00,0
9,10,9,31.57,13.27,24.25,20.95,74,1030.9,S,1,0,C.,0.00,0
10,11,9,33.09,13.30,24.20,20.56,71,1027.9,E,1,0,C.,0.00,0
11,12,9,33.25,14.10,26.49,23.76,80,1024.9,NE,2,0,C.,0.00,0
12,13,9,33.23,15.27,22.48,19.72,77,1021.2,NE,2,0,C.,0.00,0
13,14,9,33.30,15.98,24.40,21.28,76,1013.2,NE,1,1,As.,0.00,0
14,15,9,26.31,16.16,21.44,18.67,77,1006.6,NW,2,6,Sc.,0.00,0
15,16,9,23.16,15.37,18.98,16.61,81,1012.1,N,2,7,As.,1.50,0
16,17,9,17.75,14.80,14.81,14.14,93,1019.5,NNE,3,8,Sc.,0.00,0
17,18,9,24.08,15.30,18.03,16.65,87,1019.1,S,1,7,Sc.,0.00,0
18,19,9,21.85,14.32,17.61,15.49,80,1018.7,WNW,2,1,Cu.,0.00,0
19,20,9,24.56,12.13,19.73,17.19,78,1020.4,WSW,22,6,Cu.,0.00,0
20,21,9,23.04,13.38,19.41,16.99,78,1019.2,W,1,3,Cu.,0.00,0
21,22,9,24.64,12.10,19.40,15.67,67,1017.9,SSW,2,7,Cu.,1.50,0
22,23,9,25.18,17.90,22.04,18.61,72,1017.2,SSW,2,6,Cu.,0.00,0
23,24,9,24.39,19.31,20.79,18.45,80,1019.7,SW,2,8,Cc.,5.00,0
24,25,9,20.73,15.70,15.78,15.26,94,1023.6,NW,2,8,Sc.,2.50,0
25,26,9,23.59,10.47,17.00,13.67,69,1024.9,NW,1,2,Cu.,0.25,0
26,27,9,24.91,12.98,17.40,15.57,83,1025.0,NE,2,2,Cu.,0.00,0
27,28,9,24.11,11.45,17.17,15.11,80,1027.8,SSE,2,2,Ci.,0.00,0
28,29,9,20.34,14.56,18.13,15.08,72,1029.6,NE,3,7,Sc.,0.25,0
29,30,9,22.76,10.40,15.03,12.31,73,1030.7,NE,3,2,Ci.,0.00,0
30,31,9,22.99,12.17,15.58,14.01,84,1031.9,NE,3,8,Sc.,0.00,0

In [46]:
df.query('Dry_T>20.51 and Hum>75',inplace=True)
df

,Days,Time,Max_T,Min_T,Dry_T,Wet_T,Hum,Press,Wind_D.,Wind_St,Cl_am,Cl_Ty,Rain,Snow
1,2,9,26.18,18.20,21.54,19.38,82,1016.7,SW,2,8,Sc.,0.4,0
11,12,9,33.25,14.10,26.49,23.76,80,1024.9,NE,2,0,C.,0.0,0
12,13,9,33.23,15.27,22.48,19.72,77,1021.2,NE,2,0,C.,0.0,0
13,14,9,33.30,15.98,24.40,21.28,76,1013.2,NE,1,1,As.,0.0,0
14,15,9,26.31,16.16,21.44,18.67,77,1006.6,NW,2,6,Sc.,0.0,0
23,24,9,24.39,19.31,20.79,18.45,80,1019.7,SW,2,8,Cc.,5.0,0

In [47]:
import pandas as pd
df=pd.read_excel("Aug_2022.xlsx")
df

,Days,Time,Max T,Min T,Dry T,Wet T,Hum,Press,Wind D.,Wind St,Cl am,Cl Ty,Rain,Snow
0,1,9,26.43,11.78,18.97,16.22,76,1023.9,S,1,0,C.,1.00,0
1,2,9,26.18,18.20,21.54,19.38,82,1016.7,SW,2,8,Sc.,0.40,0
2,3,9,26.45,17.86,20.23,18.59,85,1016.0,WNW,2,6,Cu.,0.00,0
3,4,9,21.70,12.89,18.31,15.38,74,1020.0,NW,3,4,Cu.,0.00,0
4,5,9,20.79,10.02,15.38,13.45,81,1027.4,NW,3,4,Cu.,0.00,0
5,6,9,23.54,7.32,17.81,15.06,75,1034.9,NNW,2,3,Cu.,0.00,0
6,7,9,25.51,9.02,12.29,10.72,83,1031.9,NW,2,1,Ci.,0.00,0
7,8,9,28.49,11.47,20.51,17.57,75,1032.9,NNE,1,1,Cu.,0.00,0
8,9,9,29.43,12.41,19.03,16.16,78,1034.6,N,1,1,Ci.,0.00,0
9,10,9,31.57,13.27,24.25,20.95,74,1030.9,S,1,0,C.,0.00,0
10,11,9,33.09,13.30,24.20,20.56,71,1027.9,E,1,0,C.,0.00,0
11,12,9,33.25,14.10,26.49,23.76,80,1024.9,NE,2,0,C.,0.00,0
12,13,9,33.23,15.27,22.48,19.72,77,1021.2,NE,2,0,C.,0.00,0
13,14,9,33.30,15.98,24.40,21.28,76,1013.2,NE,1,1,As.,0.00,0
14,15,9,26.31,16.16,21.44,18.67,77,1006.6,NW,2,6,Sc.,0.00,0
15,16,9,23.16,15.37,18.98,16.61,81,1012.1,N,2,7,As.,1.50,0
16,17,9,17.75,14.80,14.81,14.14,93,1019.5,NNE,3,8,Sc.,0.00,0
17,18,9,24.08,15.30,18.03,16.65,87,1019.1,S,1,7,Sc.,0.00,0
18,19,9,21.85,14.32,17.61,15.49,80,1018.7,WNW,2,1,Cu.,0.00,0
19,20,9,24.56,12.13,19.73,17.19,78,1020.4,WSW,22,6,Cu.,0.00,0
20,21,9,23.04,13.38,19.41,16.99,78,1019.2,W,1,3,Cu.,0.00,0
21,22,9,24.64,12.10,19.40,15.67,67,1017.9,SSW,2,7,Cu.,1.50,0
22,23,9,25.18,17.90,22.04,18.61,72,1017.2,SSW,2,6,Cu.,0.00,0
23,24,9,24.39,19.31,20.79,18.45,80,1019.7,SW,2,8,Cc.,5.00,0
24,25,9,20.73,15.70,15.78,15.26,94,1023.6,NW,2,8,Sc.,2.50,0
25,26,9,23.59,10.47,17.00,13.67,69,1024.9,NW,1,2,Cu.,0.25,0
26,27,9,24.91,12.98,17.40,15.57,83,1025.0,NE,2,2,Cu.,0.00,0
27,28,9,24.11,11.45,17.17,15.11,80,1027.8,SSE,2,2,Ci.,0.00,0
28,29,9,20.34,14.56,18.13,15.08,72,1029.6,NE,3,7,Sc.,0.25,0
29,30,9,22.76,10.40,15.03,12.31,73,1030.7,NE,3,2,Ci.,0.00,0
30,31,9,22.99,12.17,15.58,14.01,84,1031.9,NE,3,8,Sc.,0.00,0

In [48]:
df.columns=[column.replace(" ","_") for column in df.columns]
df

,Days,Time,Max_T,Min_T,Dry_T,Wet_T,Hum,Press,Wind_D.,Wind_St,Cl_am,Cl_Ty,Rain,Snow
0,1,9,26.43,11.78,18.97,16.22,76,1023.9,S,1,0,C.,1.00,0
1,2,9,26.18,18.20,21.54,19.38,82,1016.7,SW,2,8,Sc.,0.40,0
2,3,9,26.45,17.86,20.23,18.59,85,1016.0,WNW,2,6,Cu.,0.00,0
3,4,9,21.70,12.89,18.31,15.38,74,1020.0,NW,3,4,Cu.,0.00,0
4,5,9,20.79,10.02,15.38,13.45,81,1027.4,NW,3,4,Cu.,0.00,0
5,6,9,23.54,7.32,17.81,15.06,75,1034.9,NNW,2,3,Cu.,0.00,0
6,7,9,25.51,9.02,12.29,10.72,83,1031.9,NW,2,1,Ci.,0.00,0
7,8,9,28.49,11.47,20.51,17.57,75,1032.9,NNE,1,1,Cu.,0.00,0
8,9,9,29.43,12.41,19.03,16.16,78,1034.6,N,1,1,Ci.,0.00,0
9,10,9,31.57,13.27,24.25,20.95,74,1030.9,S,1,0,C.,0.00,0
10,11,9,33.09,13.30,24.20,20.56,71,1027.9,E,1,0,C.,0.00,0
11,12,9,33.25,14.10,26.49,23.76,80,1024.9,NE,2,0,C.,0.00,0
12,13,9,33.23,15.27,22.48,19.72,77,1021.2,NE,2,0,C.,0.00,0
13,14,9,33.30,15.98,24.40,21.28,76,1013.2,NE,1,1,As.,0.00,0
14,15,9,26.31,16.16,21.44,18.67,77,1006.6,NW,2,6,Sc.,0.00,0
15,16,9,23.16,15.37,18.98,16.61,81,1012.1,N,2,7,As.,1.50,0
16,17,9,17.75,14.80,14.81,14.14,93,1019.5,NNE,3,8,Sc.,0.00,0
17,18,9,24.08,15.30,18.03,16.65,87,1019.1,S,1,7,Sc.,0.00,0
18,19,9,21.85,14.32,17.61,15.49,80,1018.7,WNW,2,1,Cu.,0.00,0
19,20,9,24.56,12.13,19.73,17.19,78,1020.4,WSW,22,6,Cu.,0.00,0
20,21,9,23.04,13.38,19.41,16.99,78,1019.2,W,1,3,Cu.,0.00,0
21,22,9,24.64,12.10,19.40,15.67,67,1017.9,SSW,2,7,Cu.,1.50,0
22,23,9,25.18,17.90,22.04,18.61,72,1017.2,SSW,2,6,Cu.,0.00,0
23,24,9,24.39,19.31,20.79,18.45,80,1019.7,SW,2,8,Cc.,5.00,0
24,25,9,20.73,15.70,15.78,15.26,94,1023.6,NW,2,8,Sc.,2.50,0
25,26,9,23.59,10.47,17.00,13.67,69,1024.9,NW,1,2,Cu.,0.25,0
26,27,9,24.91,12.98,17.40,15.57,83,1025.0,NE,2,2,Cu.,0.00,0
27,28,9,24.11,11.45,17.17,15.11,80,1027.8,SSE,2,2,Ci.,0.00,0
28,29,9,20.34,14.56,18.13,15.08,72,1029.6,NE,3,7,Sc.,0.25,0
29,30,9,22.76,10.40,15.03,12.31,73,1030.7,NE,3,2,Ci.,0.00,0
30,31,9,22.99,12.17,15.58,14.01,84,1031.9,NE,3,8,Sc.,0.00,0

In [49]:
df.loc[(df['Dry_T']>22.10) & (df['Hum']<88)]

,Days,Time,Max_T,Min_T,Dry_T,Wet_T,Hum,Press,Wind_D.,Wind_St,Cl_am,Cl_Ty,Rain,Snow
9,10,9,31.57,13.27,24.25,20.95,74,1030.9,S,1,0,C.,0.0,0
10,11,9,33.09,13.30,24.20,20.56,71,1027.9,E,1,0,C.,0.0,0
11,12,9,33.25,14.10,26.49,23.76,80,1024.9,NE,2,0,C.,0.0,0
12,13,9,33.23,15.27,22.48,19.72,77,1021.2,NE,2,0,C.,0.0,0
13,14,9,33.30,15.98,24.40,21.28,76,1013.2,NE,1,1,As.,0.0,0